apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: cephfs-hdd
  resources:
    requests:
      storage: 1Gi
