cluster.name: "docker-cluster"
network.host: 0.0.0.0

# Security settings
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false

# License settings
xpack.license.self_generated.type: basic

# Monitoring settings
xpack.monitoring.collection.enabled: true
