services:
  elasticsearch:
    image: elasticsearch:8.18.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "es_data_1:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      logging:
        aliases:
          - "elasticsearch"

  kibana:
    image: kibana:8.18.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL="http://elasticsearch:9300"
    ports:
      - "5601:5601"
    networks:
      logging:
        aliases:
          - "kibana"

  logstash:
    image: logstash:8.18.0
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - "./config:/etc/logstash/conf.d:Z"
    ports:
      - "5010:5000"
    networks:
      logging:
        aliases:
          - "logstash"

volumes:
  es_data_1:
    driver: local

networks:
  logging:
    name: elk_logging
    driver: bridge
