services:
  redis_server:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      cache:
        aliases:
          - "redis"

  redis_insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      cache:
        aliases:
          - "redis_insight"

  elasticsearch:
    image: elasticsearch:8.18.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "es_data_1:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: "curl -s http://localhost:9200/ | grep docker || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      logging:
        aliases:
          - "elasticsearch"

  kibana:
    image: kibana:8.18.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL="http://elasticsearch:9300"
    ports:
      - "5601:5601"
    networks:
      logging:
        aliases:
          - "kibana"

  logstash:
    image: logstash:8.18.0
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - "./config:/etc/logstash/conf.d:Z"
    ports:
      - "5010:5000"
    networks:
      logging:
        aliases:
          - "logstash"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    depends_on:
      - elasticsearch
    environment:
      - STORAGE_TYPE=elasticsearch
      - "ES_HOSTS=elasticsearch:9300"
      - JAVA_OPTS=-Xms8g -Xmx8g
    ports:
      - "9411:9411"
    networks:
      tracing:
        aliases:
          - "zipkin"
      logging:
        aliases:
          - "zipkin"

volumes:
  es_data_1:
    driver: local

networks:
  cache:
    driver: bridge
  logging:
    driver: bridge
  tracing:
    driver: bridge
