apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: rook-cephfs-retain
  resources:
    requests:
      storage: 1Gi
